# Generated for django-auth-platform v24.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_rbac_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("domain", models.CharField(choices=[("auth", "Auth"), ("billing", "Billing"), ("security", "Security"), ("compliance", "Compliance"), ("ops", "Operations"), ("platform", "Developer Platform"), ("notifications", "Notifications"), ("observability", "Observability"), ("fraud", "Fraud/Abuse"), ("custom", "Custom")], max_length=32)),
                ("widget_type", models.CharField(choices=[("metric", "Metric"), ("table", "Table"), ("queue", "Queue"), ("link", "Link"), ("chart", "Chart")], default="metric", max_length=16)),
                ("description", models.TextField(blank=True)),
                ("query_config", models.JSONField(blank=True, default=dict, help_text="Declarative backend query/card configuration. Never store secrets here.")),
                ("display_config", models.JSONField(blank=True, default=dict)),
                ("permission_code", models.CharField(blank=True, help_text="Optional RBAC permission required to see this widget.", max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_dashboard_widgets", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_dashboard_widgets", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["sort_order", "domain", "title"]},
        ),
        migrations.CreateModel(
            name="SavedAdminView",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("resource", models.CharField(help_text="Example: users, organizations, billing.subscriptions, fraud.cases", max_length=120)),
                ("visibility", models.CharField(choices=[("private", "Private"), ("team", "Team"), ("global", "Global")], default="private", max_length=16)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("sort", models.JSONField(blank=True, default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="saved_admin_views", to="accounts.organization")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_admin_views", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["resource", "name"]},
        ),
        migrations.CreateModel(
            name="OperatorTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("domain", models.CharField(choices=[("support", "Support"), ("auth", "Auth"), ("billing", "Billing"), ("security", "Security"), ("compliance", "Compliance"), ("ops", "Operations"), ("fraud", "Fraud/Abuse")], default="support", max_length=24)),
                ("priority", models.CharField(choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")], default="normal", max_length=16)),
                ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In progress"), ("blocked", "Blocked"), ("done", "Done"), ("canceled", "Canceled")], default="open", max_length=24)),
                ("description", models.TextField(blank=True)),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=128)),
                ("target_url", models.CharField(blank=True, max_length=500)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_operator_tasks", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_operator_tasks", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="operator_tasks", to="accounts.organization")),
            ],
            options={"ordering": ["status", "-priority", "due_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="BulkActionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("export_users", "Export users"), ("disable_users", "Disable users"), ("revoke_sessions", "Revoke sessions"), ("update_org_limits", "Update organization limits"), ("apply_billing_override", "Apply billing override"), ("recalculate_entitlements", "Recalculate entitlements"), ("send_notification", "Send notification"), ("custom", "Custom")], max_length=40)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("pending_approval", "Pending approval"), ("approved", "Approved"), ("rejected", "Rejected"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("canceled", "Canceled")], default="draft", max_length=24)),
                ("reason", models.TextField()),
                ("target_filter", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("estimated_count", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_summary", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_bulk_actions", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_bulk_actions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AdminNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_id", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("visibility", models.CharField(choices=[("staff", "Staff"), ("security", "Security only"), ("billing", "Billing only"), ("compliance", "Compliance only")], default="staff", max_length=24)),
                ("pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="admin_notes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-pinned", "-created_at"]},
        ),
        migrations.CreateModel(
            name="AdminWorkspacePreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("landing_page", models.CharField(default="overview", max_length=120)),
                ("timezone_name", models.CharField(default="UTC", max_length=80)),
                ("favorite_resources", models.JSONField(blank=True, default=list)),
                ("dismissed_banners", models.JSONField(blank=True, default=list)),
                ("dashboard_layout", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="admin_console_preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["user__email"]},
        ),
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="global", max_length=120)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source_counts", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_dashboard_snapshots", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-generated_at"]},
        ),
        migrations.AddIndex(model_name="dashboardwidget", index=models.Index(fields=["domain", "enabled"], name="admin_conso_domain_5c90d0_idx")),
        migrations.AddIndex(model_name="dashboardwidget", index=models.Index(fields=["permission_code"], name="admin_conso_permiss_ae8764_idx")),
        migrations.AddIndex(model_name="savedadminview", index=models.Index(fields=["resource", "visibility"], name="admin_conso_resourc_f2c519_idx")),
        migrations.AddIndex(model_name="savedadminview", index=models.Index(fields=["owner", "resource"], name="admin_conso_owner_i_b26a27_idx")),
        migrations.AddConstraint(model_name="savedadminview", constraint=models.UniqueConstraint(fields=("owner", "resource", "name"), name="unique_admin_view_per_owner_resource_name")),
        migrations.AddIndex(model_name="operatortask", index=models.Index(fields=["status", "priority"], name="admin_conso_status_34f44d_idx")),
        migrations.AddIndex(model_name="operatortask", index=models.Index(fields=["assigned_to", "status"], name="admin_conso_assigne_645b0e_idx")),
        migrations.AddIndex(model_name="operatortask", index=models.Index(fields=["domain", "status"], name="admin_conso_domain_41e0d6_idx")),
        migrations.AddIndex(model_name="operatortask", index=models.Index(fields=["organization", "status"], name="admin_conso_organiz_5f10e1_idx")),
        migrations.AddIndex(model_name="bulkactionrequest", index=models.Index(fields=["action", "status"], name="admin_conso_action__dc5588_idx")),
        migrations.AddIndex(model_name="bulkactionrequest", index=models.Index(fields=["requested_by", "status"], name="admin_conso_request_8e1730_idx")),
        migrations.AddIndex(model_name="bulkactionrequest", index=models.Index(fields=["idempotency_key"], name="admin_conso_idempot_a78232_idx")),
        migrations.AddIndex(model_name="adminnote", index=models.Index(fields=["subject_type", "subject_id"], name="admin_conso_subject_8a863c_idx")),
        migrations.AddIndex(model_name="adminnote", index=models.Index(fields=["visibility", "pinned"], name="admin_conso_visibil_c2c089_idx")),
        migrations.AddIndex(model_name="dashboardsnapshot", index=models.Index(fields=["name", "generated_at"], name="admin_conso_name_0afc2a_idx")),
    ]
