from django.urls import path

from .views import (
    AccountDeletionCancelView,
    AccountDeletionConfirmView,
    AccountDeletionRequestListCreateView,
    AuditLogListView,
    AuthReadinessView,
    TenantAuthorizationReadinessView,
    AuthSessionDeviceListView,
    AuthSessionDeviceRevokeView,
    ConfirmEmailView,
    DataExportPayloadView,
    DataExportRequestListCreateView,
    EmailTokenRefreshView,
    LogoutView,
    MeView,
    MfaConfirmSetupView,
    MfaDisableView,
    MfaRegenerateRecoveryCodesView,
    MfaStartSetupView,
    MfaStatusView,
    OAuthAuthorizeView,
    OAuthClientListCreateView,
    OAuthDiscoveryView,
    OAuthJwksView,
    OAuthTokenActivityListView,
    OAuthTokenView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PrivacyPreferenceView,
    PublicProfileView,
    RefreshTokenFamilyListView,
    RegisterView,
    RevokeAllRefreshTokensView,
    ResendEmailVerificationView,
    ServiceCredentialDeactivateView,
    ServiceCredentialListCreateView,
    ServiceCredentialRotateView,
    ServiceTokenView,
    SessionLoginView,
    SessionLogoutView,
    SessionStatusView,
    TokenIntrospectionView,
    TokenLoginView,
    TokenRevocationView,
    UserConsentListCreateView,
    health_check,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/readiness/", AuthReadinessView.as_view(), name="auth-readiness"),
    path("tenancy/readiness/", TenantAuthorizationReadinessView.as_view(), name="tenant-authorization-readiness"),
    path("auth/token/", TokenLoginView.as_view(), name="token-obtain-pair"),
    path("auth/token/refresh/", EmailTokenRefreshView.as_view(), name="token-refresh"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/session/login/", SessionLoginView.as_view(), name="session-login"),
    path("auth/session/logout/", SessionLogoutView.as_view(), name="session-logout"),
    path("auth/session/status/", SessionStatusView.as_view(), name="session-status"),
    path("auth/sessions/devices/", AuthSessionDeviceListView.as_view(), name="auth-session-devices"),
    path("auth/sessions/devices/<uuid:device_id>/revoke/", AuthSessionDeviceRevokeView.as_view(), name="auth-session-device-revoke"),
    path("auth/tokens/refresh-families/", RefreshTokenFamilyListView.as_view(), name="auth-refresh-token-families"),
    path("auth/tokens/refresh-families/revoke-all/", RevokeAllRefreshTokensView.as_view(), name="auth-refresh-token-revoke-all"),
    path("auth/email/verify/resend/", ResendEmailVerificationView.as_view(), name="email-verify-resend"),
    path("auth/email/verify/confirm/", ConfirmEmailView.as_view(), name="email-verify-confirm"),
    path("auth/password/reset/request/", PasswordResetRequestView.as_view(), name="password-reset-request"),
    path("auth/password/reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("auth/mfa/status/", MfaStatusView.as_view(), name="mfa-status"),
    path("auth/mfa/setup/start/", MfaStartSetupView.as_view(), name="mfa-setup-start"),
    path("auth/mfa/setup/confirm/", MfaConfirmSetupView.as_view(), name="mfa-setup-confirm"),
    path("auth/mfa/recovery-codes/regenerate/", MfaRegenerateRecoveryCodesView.as_view(), name="mfa-recovery-codes-regenerate"),
    path("auth/mfa/disable/", MfaDisableView.as_view(), name="mfa-disable"),
    path("oauth/clients/", OAuthClientListCreateView.as_view(), name="oauth-clients"),
    path("oauth/tokens/", OAuthTokenActivityListView.as_view(), name="oauth-token-activity"),
    path("oauth/introspect/", TokenIntrospectionView.as_view(), name="oauth-token-introspect"),
    path("oauth/revoke/", TokenRevocationView.as_view(), name="oauth-token-revoke"),
    path("service/credentials/", ServiceCredentialListCreateView.as_view(), name="service-credentials"),
    path("service/credentials/<uuid:credential_id>/rotate/", ServiceCredentialRotateView.as_view(), name="service-credential-rotate"),
    path("service/credentials/<uuid:credential_id>/deactivate/", ServiceCredentialDeactivateView.as_view(), name="service-credential-deactivate"),
    path("service/token/", ServiceTokenView.as_view(), name="service-token"),
    path("audit/logs/", AuditLogListView.as_view(), name="audit-logs"),
    path("oauth/authorize/", OAuthAuthorizeView.as_view(), name="oauth-authorize"),
    path("oauth/token/", OAuthTokenView.as_view(), name="oauth-token"),
    path("oauth/jwks/", OAuthJwksView.as_view(), name="oauth-jwks"),
    path(".well-known/openid-configuration", OAuthDiscoveryView.as_view(), name="oauth-discovery"),
    path("privacy/preferences/", PrivacyPreferenceView.as_view(), name="privacy-preferences"),
    path("privacy/consents/", UserConsentListCreateView.as_view(), name="privacy-consents"),
    path("privacy/data-exports/", DataExportRequestListCreateView.as_view(), name="privacy-data-exports"),
    path("privacy/data-export-payload/", DataExportPayloadView.as_view(), name="privacy-data-export-payload"),
    path("privacy/account-deletion/", AccountDeletionRequestListCreateView.as_view(), name="privacy-account-deletion"),
    path("privacy/account-deletion/confirm/", AccountDeletionConfirmView.as_view(), name="privacy-account-deletion-confirm"),
    path("privacy/account-deletion/cancel/", AccountDeletionCancelView.as_view(), name="privacy-account-deletion-cancel"),
    path("users/me/", MeView.as_view(), name="users-me"),
    path("users/<uuid:user_id>/public/", PublicProfileView.as_view(), name="users-public-profile"),
]

from .views import (
    OrganizationDetailView,
    OrganizationInvitationAcceptView,
    OrganizationInvitationListCreateView,
    OrganizationListCreateView,
    OrganizationMembershipListView,
    OrganizationMembershipUpdateView,
    TenantServiceCredentialDeactivateView,
    TenantServiceCredentialListCreateView,
    TenantServiceCredentialRotateView,
    PermissionCatalogView,
    PermissionPolicyDetailView,
    PermissionPolicyListCreateView,
    RolePermissionGrantListCreateView,
    RolePermissionMatrixView,
    OrganizationAccessCheckView,
    OrganizationPermissionSummaryView,
)

urlpatterns += [
    path("orgs/", OrganizationListCreateView.as_view(), name="organizations"),
    path("orgs/invitations/accept/", OrganizationInvitationAcceptView.as_view(), name="organization-invitation-accept"),
    path("orgs/<slug:slug>/", OrganizationDetailView.as_view(), name="organization-detail"),
    path("orgs/<slug:slug>/members/", OrganizationMembershipListView.as_view(), name="organization-members"),
    path("orgs/<slug:slug>/members/<uuid:membership_id>/", OrganizationMembershipUpdateView.as_view(), name="organization-member-update"),
    path("orgs/<slug:slug>/invitations/", OrganizationInvitationListCreateView.as_view(), name="organization-invitations"),
    path("orgs/<slug:slug>/service-credentials/", TenantServiceCredentialListCreateView.as_view(), name="tenant-service-credentials"),
    path("orgs/<slug:slug>/service-credentials/<uuid:credential_id>/rotate/", TenantServiceCredentialRotateView.as_view(), name="tenant-service-credential-rotate"),
    path("orgs/<slug:slug>/service-credentials/<uuid:credential_id>/deactivate/", TenantServiceCredentialDeactivateView.as_view(), name="tenant-service-credential-deactivate"),

    path("permissions/catalog/", PermissionCatalogView.as_view(), name="permission-catalog"),
    path("orgs/<slug:slug>/permissions/me/", OrganizationPermissionSummaryView.as_view(), name="organization-permissions-me"),
    path("orgs/<slug:slug>/permissions/check/", OrganizationAccessCheckView.as_view(), name="organization-access-check"),
    path("orgs/<slug:slug>/permissions/policies/", PermissionPolicyListCreateView.as_view(), name="organization-permission-policies"),
    path("orgs/<slug:slug>/permissions/policies/<uuid:policy_id>/", PermissionPolicyDetailView.as_view(), name="organization-permission-policy-detail"),
    path("orgs/<slug:slug>/permissions/grants/", RolePermissionGrantListCreateView.as_view(), name="organization-role-permission-grants"),
    path("orgs/<slug:slug>/permissions/matrix/", RolePermissionMatrixView.as_view(), name="organization-role-permission-matrix"),
]
