import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_rbac_policies"),
    ]
    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["code"], "indexes": [models.Index(fields=["code"], name="billing_pro_code_idx"), models.Index(fields=["is_active"], name="billing_pro_is_acti_idx")]},
        ),
        migrations.CreateModel(
            name="BillingCustomer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("billing_name", models.CharField(blank=True, max_length=180)),
                ("provider", models.CharField(default="manual", max_length=40)),
                ("provider_customer_id", models.CharField(blank=True, max_length=180)),
                ("tax_id", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="billing_customer", to="accounts.organization")),
                ("user", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="billing_customer", to=settings.AUTH_USER_MODEL)),
            ],
            options={"indexes": [models.Index(fields=["provider", "provider_customer_id"], name="billing_cus_provide_idx"), models.Index(fields=["billing_email"], name="billing_cus_billing_idx")]},
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("visibility", models.CharField(choices=[("public", "Public"), ("private", "Private/admin assigned"), ("internal", "Internal")], default="public", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("trial_days", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_plans_created", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="plans", to="billing.project")),
            ],
            options={"ordering": ["project__code", "code"], "indexes": [models.Index(fields=["code"], name="billing_pla_code_idx"), models.Index(fields=["project", "is_active"], name="billing_pla_project_idx"), models.Index(fields=["visibility", "is_active"], name="billing_pla_visibil_idx")]},
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=120, unique=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("interval", models.CharField(choices=[("month", "Monthly"), ("year", "Yearly"), ("one_time", "One time"), ("custom", "Custom/manual")], default="month", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("is_custom", models.BooleanField(default=False)),
                ("provider_price_id", models.CharField(blank=True, max_length=180)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_prices_created", to=settings.AUTH_USER_MODEL)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prices", to="billing.plan")),
            ],
            options={"ordering": ["plan", "amount_cents"], "indexes": [models.Index(fields=["plan", "is_active"], name="billing_pri_plan_id_idx"), models.Index(fields=["currency", "amount_cents"], name="billing_pri_currenc_idx"), models.Index(fields=["provider_price_id"], name="billing_pri_provide_idx")]},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("trialing", "Trialing"), ("active", "Active"), ("past_due", "Past due"), ("paused", "Paused"), ("cancelled", "Cancelled"), ("expired", "Expired"), ("free", "Free/manual")], default="active", max_length=24)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(default="manual", max_length=40)),
                ("provider_subscription_id", models.CharField(blank=True, max_length=180)),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_subscriptions_created", to=settings.AUTH_USER_MODEL)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="billing.billingcustomer")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="billing.plan")),
                ("price", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="billing.price")),
            ],
            options={"ordering": ["-created_at"], "indexes": [models.Index(fields=["customer", "status"], name="billing_sub_custome_idx"), models.Index(fields=["plan", "status"], name="billing_sub_plan_id_idx"), models.Index(fields=["provider", "provider_subscription_id"], name="billing_sub_provide_idx"), models.Index(fields=["current_period_end"], name="billing_sub_current_idx")]},
        ),
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=140)),
                ("value_type", models.CharField(choices=[("boolean", "Boolean"), ("integer", "Integer"), ("string", "String")], default="boolean", max_length=16)),
                ("bool_value", models.BooleanField(default=False)),
                ("int_value", models.IntegerField(blank=True, null=True)),
                ("str_value", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="entitlements", to="billing.plan")),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="entitlements", to="billing.subscription")),
            ],
            options={"indexes": [models.Index(fields=["key"], name="billing_ent_key_idx"), models.Index(fields=["plan", "key"], name="billing_ent_plan_id_idx"), models.Index(fields=["subscription", "key"], name="billing_ent_subscri_idx")]},
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(default="manual", max_length=40)),
                ("provider_invoice_id", models.CharField(blank=True, max_length=180)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("open", "Open"), ("paid", "Paid"), ("void", "Void"), ("uncollectible", "Uncollectible")], default="draft", max_length=24)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount_due_cents", models.PositiveIntegerField(default=0)),
                ("amount_paid_cents", models.PositiveIntegerField(default=0)),
                ("hosted_invoice_url", models.URLField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="billing.billingcustomer")),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoices", to="billing.subscription")),
            ],
            options={"ordering": ["-created_at"], "indexes": [models.Index(fields=["customer", "created_at"], name="billing_inv_custome_idx"), models.Index(fields=["provider", "provider_invoice_id"], name="billing_inv_provide_idx"), models.Index(fields=["status"], name="billing_inv_status_idx")]},
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(default="manual", max_length=40)),
                ("provider_payment_id", models.CharField(blank=True, max_length=180)),
                ("status", models.CharField(choices=[("requires_action", "Requires action"), ("processing", "Processing"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("refunded", "Refunded")], default="processing", max_length=32)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_transactions", to="billing.billingcustomer")),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="billing.invoice")),
            ],
            options={"ordering": ["-created_at"], "indexes": [models.Index(fields=["customer", "created_at"], name="billing_pay_custome_idx"), models.Index(fields=["provider", "provider_payment_id"], name="billing_pay_provide_idx"), models.Index(fields=["status"], name="billing_pay_status_idx")]},
        ),
        migrations.CreateModel(
            name="BillingWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=40)),
                ("event_id", models.CharField(max_length=180)),
                ("event_type", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("received", "Received"), ("processed", "Processed"), ("failed", "Failed"), ("ignored", "Ignored")], default="received", max_length=16)),
                ("payload", models.JSONField(default=dict)),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("provider", "event_id")}, "indexes": [models.Index(fields=["provider", "event_id"], name="billing_web_provide_idx"), models.Index(fields=["event_type"], name="billing_web_event_t_idx"), models.Index(fields=["status"], name="billing_web_status_idx")]},
        ),
        migrations.AddConstraint(model_name="entitlement", constraint=models.UniqueConstraint(fields=("plan", "key"), name="uniq_plan_entitlement_key")),
        migrations.AddConstraint(model_name="entitlement", constraint=models.UniqueConstraint(fields=("subscription", "key"), name="uniq_subscription_entitlement_key")),
    ]
