# Generated for django-auth-platform v14.

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_rbac_policies"),
        ("billing", "0004_invoice_tax_refund_dunning"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("billing_mode", models.CharField(choices=[("recurring", "Recurring"), ("one_time", "One time"), ("metered", "Metered")], default="recurring", max_length=20)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("unit_amount_cents", models.PositiveIntegerField(default=0)),
                ("provider_price_id", models.CharField(blank=True, max_length=180)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="addons", to="billing.project")),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("discount_type", models.CharField(choices=[("percent", "Percent"), ("fixed", "Fixed amount"), ("free", "Free override")], max_length=20)),
                ("percent_off", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("amount_off_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("duration", models.CharField(choices=[("once", "Once"), ("repeating", "Repeating"), ("forever", "Forever")], default="once", max_length=20)),
                ("duration_months", models.PositiveIntegerField(blank=True, null=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("redeemed_count", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applies_to_plans", models.ManyToManyField(blank=True, related_name="discounts", to="billing.plan")),
                ("applies_to_projects", models.ManyToManyField(blank=True, related_name="discounts", to="billing.project")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_discounts_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="EntitlementSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payload", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("calculated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=180)),
                ("customer", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="entitlement_snapshot", to="billing.billingcustomer")),
            ],
        ),
        migrations.CreateModel(
            name="PromotionCode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("redeemed_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discount", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promotion_codes", to="billing.discount")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="promotion_codes", to="accounts.organization")),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="AddOnEntitlement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=140)),
                ("value_type", models.CharField(choices=[("boolean", "Boolean"), ("integer", "Integer"), ("string", "String")], default="integer", max_length=16)),
                ("bool_value", models.BooleanField(default=False)),
                ("int_value", models.IntegerField(blank=True, null=True)),
                ("str_value", models.CharField(blank=True, max_length=255)),
                ("is_incremental", models.BooleanField(default=True, help_text="When true, integer values are multiplied by quantity and added to the base entitlement.")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("addon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entitlements", to="billing.addon")),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionAddOn",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("cancelled", "Cancelled")], default="active", max_length=20)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_amount_cents", models.PositiveIntegerField(default=0)),
                ("provider", models.CharField(default="manual", max_length=40)),
                ("provider_subscription_item_id", models.CharField(blank=True, max_length=180)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("addon", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_addons", to="billing.addon")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_subscription_addons_created", to=settings.AUTH_USER_MODEL)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addons", to="billing.subscription")),
            ],
            options={"ordering": ["subscription", "addon__code"]},
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.CharField(blank=True, max_length=180)),
                ("original_amount_cents", models.PositiveIntegerField(default=0)),
                ("discount_amount_cents", models.PositiveIntegerField(default=0)),
                ("final_amount_cents", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("redeemed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="discount_redemptions", to="billing.billingcustomer")),
                ("discount", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="redemptions", to="billing.discount")),
                ("price", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="discount_redemptions", to="billing.price")),
                ("promotion_code", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="redemptions", to="billing.promotioncode")),
                ("redeemed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="billing_discounts_redeemed", to=settings.AUTH_USER_MODEL)),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="discount_redemptions", to="billing.subscription")),
            ],
            options={"ordering": ["-redeemed_at"]},
        ),
        migrations.AddIndex(model_name="addon", index=models.Index(fields=["code", "is_active"], name="billing_add_code_191f4b_idx")),
        migrations.AddIndex(model_name="addon", index=models.Index(fields=["project", "is_active"], name="billing_add_project_ef4e65_idx")),
        migrations.AddIndex(model_name="discount", index=models.Index(fields=["code", "is_active"], name="billing_dis_code_d62f84_idx")),
        migrations.AddIndex(model_name="discount", index=models.Index(fields=["starts_at", "expires_at"], name="billing_dis_starts_a_0a39b7_idx")),
        migrations.AddIndex(model_name="discount", index=models.Index(fields=["discount_type"], name="billing_dis_discoun_6618a7_idx")),
        migrations.AddIndex(model_name="entitlementsnapshot", index=models.Index(fields=["calculated_at"], name="billing_ent_calcula_24bb3b_idx")),
        migrations.AddIndex(model_name="entitlementsnapshot", index=models.Index(fields=["invalidated_at"], name="billing_ent_invalid_4f8100_idx")),
        migrations.AddIndex(model_name="promotioncode", index=models.Index(fields=["code", "is_active"], name="billing_pro_code_99afda_idx")),
        migrations.AddIndex(model_name="promotioncode", index=models.Index(fields=["organization", "is_active"], name="billing_pro_organiz_d95e61_idx")),
        migrations.AddIndex(model_name="addonentitlement", index=models.Index(fields=["addon", "key"], name="billing_add_addon_i_9a00ad_idx")),
        migrations.AddConstraint(model_name="addonentitlement", constraint=models.UniqueConstraint(fields=("addon", "key"), name="uniq_addon_entitlement_key")),
        migrations.AddIndex(model_name="subscriptionaddon", index=models.Index(fields=["subscription", "status"], name="billing_sub_subscri_611f37_idx")),
        migrations.AddIndex(model_name="subscriptionaddon", index=models.Index(fields=["addon", "status"], name="billing_sub_addon_i_027ea1_idx")),
        migrations.AddIndex(model_name="subscriptionaddon", index=models.Index(fields=["provider", "provider_subscription_item_id"], name="billing_sub_provide_a4a322_idx")),
        migrations.AddConstraint(model_name="subscriptionaddon", constraint=models.UniqueConstraint(fields=("subscription", "addon"), name="uniq_subscription_addon")),
        migrations.AddIndex(model_name="discountredemption", index=models.Index(fields=["customer", "redeemed_at"], name="billing_dis_custome_fb46f6_idx")),
        migrations.AddIndex(model_name="discountredemption", index=models.Index(fields=["discount", "redeemed_at"], name="billing_dis_discoun_a350f6_idx")),
        migrations.AddConstraint(model_name="discountredemption", constraint=models.UniqueConstraint(fields=("customer", "discount", "idempotency_key"), name="uniq_discount_redemption_idempotency")),
    ]
