from rest_framework import permissions, response, views, viewsets
from rest_framework.decorators import action

from admin_integration.permissions import ADMIN_SERVICE_AUTHENTICATION_CLASSES, StaffOrAdminServiceScope
from .checks import feature_flag_inventory, run_production_verification
from .models import FeatureFlagInventory, VerificationSnapshot
from .serializers import FeatureFlagInventorySerializer, VerificationSnapshotSerializer


class StaffOnly(permissions.BasePermission):
    def has_permission(self, request, view):
        return bool(request.user and request.user.is_authenticated and request.user.is_staff)


class ProductionVerificationView(views.APIView):
    authentication_classes = ADMIN_SERVICE_AUTHENTICATION_CLASSES
    permission_classes = [StaffOrAdminServiceScope]
    required_admin_scopes = ["admin:readiness"]

    def get(self, request):
        return response.Response(run_production_verification())

    def post(self, request):
        result = run_production_verification()
        snapshot = VerificationSnapshot.objects.create(
            status=result["status"],
            summary=result["summary"],
            checks=result["checks"],
            created_by=request.user if request.user.is_authenticated else None,
        )
        return response.Response(VerificationSnapshotSerializer(snapshot).data, status=201)


class VerificationSnapshotViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = VerificationSnapshot.objects.all()
    serializer_class = VerificationSnapshotSerializer
    permission_classes = [StaffOnly]


class FeatureFlagInventoryViewSet(viewsets.ModelViewSet):
    queryset = FeatureFlagInventory.objects.all()
    serializer_class = FeatureFlagInventorySerializer
    permission_classes = [StaffOnly]

    @action(detail=False, methods=["post"], url_path="sync")
    def sync(self, request):
        for row in feature_flag_inventory():
            FeatureFlagInventory.objects.update_or_create(
                app_label=row["app_label"],
                defaults={
                    "tier": row["tier"],
                    "enabled_by_default": row["enabled_by_default"],
                    "notes": "Generated by v42 production verification inventory.",
                },
            )
        return response.Response({"synced": True, "items": feature_flag_inventory()})
