# Generated for django-auth-platform v27.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_rbac_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseIdentityProvider",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=80)),
                ("protocol", models.CharField(choices=[("saml2", "SAML 2.0"), ("oidc", "OpenID Connect")], default="saml2", max_length=16)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("testing", "Testing"), ("active", "Active"), ("suspended", "Suspended"), ("disabled", "Disabled")], default="draft", max_length=16)),
                ("entity_id", models.CharField(blank=True, max_length=500)),
                ("sso_url", models.URLField(blank=True)),
                ("slo_url", models.URLField(blank=True)),
                ("x509_certificate_fingerprint", models.CharField(blank=True, max_length=160)),
                ("x509_certificate_pem", models.TextField(blank=True, help_text="Store encrypted-at-rest in production if certificates contain sensitive metadata.")),
                ("metadata_url", models.URLField(blank=True)),
                ("metadata_xml", models.TextField(blank=True)),
                ("oidc_issuer", models.URLField(blank=True)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("client_secret_hash", models.CharField(blank=True, max_length=256)),
                ("default_role", models.CharField(default="member", max_length=16)),
                ("allowed_groups", models.JSONField(blank=True, default=list)),
                ("attribute_mapping", models.JSONField(blank=True, default=dict)),
                ("require_signed_assertions", models.BooleanField(default=True)),
                ("require_encrypted_assertions", models.BooleanField(default=False)),
                ("allow_idp_initiated_login", models.BooleanField(default=False)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enterprise_idps_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enterprise_identity_providers", to="accounts.organization")),
            ],
            options={"ordering": ["organization__slug", "name"], "unique_together": {("organization", "slug")}},
        ),
        migrations.CreateModel(
            name="VerifiedDomain",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("domain", models.CharField(max_length=255)),
                ("method", models.CharField(choices=[("dns_txt", "DNS TXT"), ("http_file", "HTTP file"), ("manual", "Manual review")], default="dns_txt", max_length=24)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("verified", "Verified"), ("failed", "Failed"), ("revoked", "Revoked")], default="pending", max_length=16)),
                ("verification_token_prefix", models.CharField(blank=True, db_index=True, max_length=32)),
                ("verification_token_hash", models.CharField(blank=True, max_length=256)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="verified_domains", to="accounts.organization")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="enterprise_domains_verified", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["domain"], "unique_together": {("organization", "domain")}},
        ),
        migrations.CreateModel(
            name="SsoPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("enforcement", models.CharField(choices=[("optional", "Optional"), ("required_for_domain", "Required for verified domains"), ("required_for_all", "Required for all members")], default="optional", max_length=32)),
                ("allow_password_fallback_for_owners", models.BooleanField(default=True)),
                ("allow_jit_provisioning", models.BooleanField(default=False)),
                ("require_verified_domain_for_jit", models.BooleanField(default=True)),
                ("require_mfa_after_sso", models.BooleanField(default=False)),
                ("allowed_email_domains", models.JSONField(blank=True, default=list)),
                ("blocked_email_domains", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_identity_provider", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_for_policies", to="enterprise_sso.enterpriseidentityprovider")),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="sso_policy", to="accounts.organization")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sso_policies_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["organization__slug"]},
        ),
        migrations.CreateModel(
            name="JitProvisioningRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled")], default="active", max_length=16)),
                ("claim", models.CharField(default="groups", max_length=120)),
                ("operator", models.CharField(default="contains", max_length=24)),
                ("value", models.CharField(max_length=255)),
                ("assigned_role", models.CharField(default="member", max_length=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identity_provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jit_rules", to="enterprise_sso.enterpriseidentityprovider")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jit_rules", to="accounts.organization")),
            ],
            options={"ordering": ["organization__slug", "priority", "name"]},
        ),
        migrations.CreateModel(
            name="SsoLoginEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("result", models.CharField(choices=[("success", "Success"), ("failure", "Failure"), ("blocked", "Blocked"), ("test", "Test")], max_length=16)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("identity_provider", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="login_events", to="enterprise_sso.enterpriseidentityprovider")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sso_login_events", to="accounts.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sso_login_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="enterpriseidentityprovider", index=models.Index(fields=["organization", "status"], name="enterprise__organiz_3ecb69_idx")),
        migrations.AddIndex(model_name="enterpriseidentityprovider", index=models.Index(fields=["protocol", "status"], name="enterprise__protoco_47358d_idx")),
        migrations.AddIndex(model_name="enterpriseidentityprovider", index=models.Index(fields=["entity_id"], name="enterprise__entity__946c28_idx")),
        migrations.AddIndex(model_name="verifieddomain", index=models.Index(fields=["domain", "status"], name="enterprise__domain_8aa033_idx")),
        migrations.AddIndex(model_name="verifieddomain", index=models.Index(fields=["organization", "status"], name="enterprise__organiz_096a64_idx")),
        migrations.AddIndex(model_name="jitprovisioningrule", index=models.Index(fields=["organization", "status"], name="enterprise__organiz_657b4a_idx")),
        migrations.AddIndex(model_name="jitprovisioningrule", index=models.Index(fields=["identity_provider", "status"], name="enterprise__identit_6f1a21_idx")),
        migrations.AddIndex(model_name="ssologinevent", index=models.Index(fields=["organization", "created_at"], name="enterprise__organiz_30efdc_idx")),
        migrations.AddIndex(model_name="ssologinevent", index=models.Index(fields=["identity_provider", "created_at"], name="enterprise__identit_724c79_idx")),
        migrations.AddIndex(model_name="ssologinevent", index=models.Index(fields=["email", "created_at"], name="enterprise__email_64ee99_idx")),
        migrations.AddIndex(model_name="ssologinevent", index=models.Index(fields=["result", "created_at"], name="enterprise__result_996c41_idx")),
    ]
