# Generated for django-auth-platform v26.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_rbac_policies"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, max_length=160)),
                ("credential_id_prefix", models.CharField(db_index=True, max_length=32)),
                ("credential_id_hash", models.CharField(max_length=256, unique=True)),
                ("public_key_jwk", models.JSONField(blank=True, default=dict, help_text="Validated public key material in provider-neutral form.")),
                ("sign_count", models.BigIntegerField(default=0)),
                ("transports", models.JSONField(blank=True, default=list)),
                ("platform", models.CharField(choices=[("web", "Web"), ("android", "Android"), ("windows", "Windows"), ("cross_platform", "Cross-platform"), ("unknown", "Unknown")], default="unknown", max_length=32)),
                ("attestation_type", models.CharField(blank=True, max_length=80)),
                ("aaguid", models.CharField(blank=True, max_length=80)),
                ("backup_eligible", models.BooleanField(default=False)),
                ("backup_state", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled"), ("revoked", "Revoked")], default="active", max_length=16)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="passkey_credentials", to="accounts.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="passkey_credentials", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PasskeyChallenge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("purpose", models.CharField(choices=[("registration", "Registration"), ("authentication", "Authentication"), ("step_up", "Step-up")], max_length=24)),
                ("challenge_prefix", models.CharField(db_index=True, max_length=32)),
                ("challenge_hash", models.CharField(max_length=256, unique=True)),
                ("rp_id", models.CharField(max_length=255)),
                ("origin", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="passkey_challenges", to="accounts.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="passkey_challenges", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("device_hash", models.CharField(max_length=256, unique=True)),
                ("device_prefix", models.CharField(db_index=True, max_length=32)),
                ("platform", models.CharField(choices=[("web", "Web"), ("android", "Android"), ("windows", "Windows"), ("api", "API"), ("unknown", "Unknown")], default="unknown", max_length=24)),
                ("trust_level", models.CharField(choices=[("low", "Low"), ("standard", "Standard"), ("high", "High")], default="standard", max_length=16)),
                ("status", models.CharField(choices=[("active", "Active"), ("untrusted", "Untrusted"), ("revoked", "Revoked"), ("expired", "Expired")], default="active", max_length=16)),
                ("last_seen_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_seen_user_agent", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="trusted_devices", to="accounts.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="trusted_devices", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-last_seen_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="StepUpPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("trigger", models.CharField(choices=[("billing_change", "Billing change"), ("password_change", "Password change"), ("mfa_change", "MFA change"), ("api_key_create", "API key create"), ("admin_action", "Admin action"), ("security_review", "Security review"), ("custom", "Custom")], max_length=32)),
                ("required_method", models.CharField(choices=[("password", "Password"), ("totp", "TOTP"), ("passkey", "Passkey"), ("recovery_code", "Recovery code"), ("any_strong", "Any strong method")], default="any_strong", max_length=24)),
                ("max_age_seconds", models.PositiveIntegerField(default=900)),
                ("min_risk_score", models.PositiveIntegerField(default=0)),
                ("is_enforced", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="step_up_policies", to="accounts.organization")),
            ],
            options={"ordering": ["organization_id", "trigger", "name"]},
        ),
        migrations.CreateModel(
            name="StepUpSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=24)),
                ("trigger", models.CharField(max_length=64)),
                ("risk_score", models.PositiveIntegerField(default=0)),
                ("satisfied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="step_up_sessions", to="accounts.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="step_up_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AccountRecoveryPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled"), ("review_required", "Review required")], default="active", max_length=24)),
                ("allowed_methods", models.JSONField(blank=True, default=list)),
                ("require_operator_review", models.BooleanField(default=False)),
                ("require_mfa_reset_delay", models.BooleanField(default=True)),
                ("cooldown_hours", models.PositiveIntegerField(default=24)),
                ("recovery_contact_email", models.EmailField(blank=True, max_length=254)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="recovery_policies", to="accounts.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="recovery_policies", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="IdentityAssuranceEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=120)),
                ("result", models.CharField(choices=[("success", "Success"), ("failed", "Failed"), ("blocked", "Blocked"), ("review", "Review")], max_length=16)),
                ("method", models.CharField(blank=True, max_length=32)),
                ("risk_score", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="identity_assurance_events", to="accounts.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="identity_assurance_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="passkeycredential", index=models.Index(fields=["user", "status"], name="identity_ha_user_id_2d41f9_idx")),
        migrations.AddIndex(model_name="passkeycredential", index=models.Index(fields=["organization", "status"], name="identity_ha_organiz_4fd219_idx")),
        migrations.AddIndex(model_name="passkeycredential", index=models.Index(fields=["credential_id_prefix"], name="identity_ha_credent_0b28df_idx")),
        migrations.AddIndex(model_name="passkeychallenge", index=models.Index(fields=["user", "purpose", "created_at"], name="identity_ha_user_id_e8d901_idx")),
        migrations.AddIndex(model_name="passkeychallenge", index=models.Index(fields=["challenge_prefix"], name="identity_ha_challen_6ad9b5_idx")),
        migrations.AddIndex(model_name="trusteddevice", index=models.Index(fields=["user", "status"], name="identity_ha_user_id_9d7788_idx")),
        migrations.AddIndex(model_name="trusteddevice", index=models.Index(fields=["organization", "status"], name="identity_ha_organiz_6ec7ef_idx")),
        migrations.AddIndex(model_name="trusteddevice", index=models.Index(fields=["device_prefix"], name="identity_ha_device__e0b3b0_idx")),
        migrations.AddIndex(model_name="stepuppolicy", index=models.Index(fields=["organization", "trigger", "is_enforced"], name="identity_ha_organiz_dd0342_idx")),
        migrations.AddIndex(model_name="stepupsession", index=models.Index(fields=["user", "trigger", "expires_at"], name="identity_ha_user_id_0315e3_idx")),
        migrations.AddIndex(model_name="stepupsession", index=models.Index(fields=["organization", "trigger"], name="identity_ha_organiz_0cf44e_idx")),
        migrations.AddIndex(model_name="accountrecoverypolicy", index=models.Index(fields=["user", "status"], name="identity_ha_user_id_7901fb_idx")),
        migrations.AddIndex(model_name="accountrecoverypolicy", index=models.Index(fields=["organization", "status"], name="identity_ha_organiz_7e4559_idx")),
        migrations.AddIndex(model_name="identityassuranceevent", index=models.Index(fields=["user", "event_type", "created_at"], name="identity_ha_user_id_5e82e8_idx")),
        migrations.AddIndex(model_name="identityassuranceevent", index=models.Index(fields=["organization", "event_type", "created_at"], name="identity_ha_organiz_e15137_idx")),
        migrations.AddIndex(model_name="identityassuranceevent", index=models.Index(fields=["result", "risk_score"], name="identity_ha_result_53e0be_idx")),
    ]
