from django.urls import path

from .views import (
    BillingReadinessView,
    BillingCustomerListView,
    CheckoutSessionListView,
    CreateCheckoutSessionView,
    CreateCustomerPortalSessionView,
    CustomerPortalSessionListView,
    BillingWebhookEventListView,
    BillingProfileListCreateView,
    CustomerTaxIdListCreateView,
    CreditNoteListView,
    IssueCreditNoteView,
    RefundRequestListCreateView,
    ReviewRefundRequestView,
    DunningCaseListCreateView,
    EntitlementListCreateView,
    InvoiceListView,
    ManualSubscriptionGrantView,
    OrganizationBillingSummaryView,
    OrganizationEntitlementsView,
    PaymentTransactionListView,
    PlanDetailView,
    PlanListCreateView,
    PriceListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    PublicPlanListView,
    SubscriptionListView,
    StripeWebhookView,
    SubscriptionChangeRequestListCreateView,
    ApplySubscriptionChangeView,
    UsageMetricListCreateView,
    UsageRecordListView,
    RecordUsageView,
    OrganizationUsageSummaryView,
    DiscountListCreateView, PromotionCodeListCreateView, DiscountRedemptionListView, RedeemDiscountView,
    AddOnListCreateView, AddOnEntitlementListCreateView, SubscriptionAddOnListView, AttachSubscriptionAddOnView,
    EntitlementSnapshotListView, RecalculateEntitlementSnapshotView, OrganizationEntitlementSnapshotView, BillingOutboxEventListCreateView, DispatchBillingOutboxView, ProviderSyncStateListCreateView, WebhookReplayRequestListView, CreateWebhookReplayRequestView, EntitlementChangeLogListView, RecalculateEntitlementSnapshotWithLogView,
)

urlpatterns = [
    path("readiness/", BillingReadinessView.as_view(), name="billing-readiness"),
    path("public/plans/", PublicPlanListView.as_view(), name="billing-public-plans"),
    path("projects/", ProjectListCreateView.as_view(), name="billing-projects"),
    path("projects/<slug:code>/", ProjectDetailView.as_view(), name="billing-project-detail"),
    path("plans/", PlanListCreateView.as_view(), name="billing-plans"),
    path("plans/<slug:code>/", PlanDetailView.as_view(), name="billing-plan-detail"),
    path("prices/", PriceListCreateView.as_view(), name="billing-prices"),
    path("entitlements/", EntitlementListCreateView.as_view(), name="billing-entitlements"),
    path("customers/", BillingCustomerListView.as_view(), name="billing-customers"),
    path("profiles/", BillingProfileListCreateView.as_view(), name="billing-profiles"),
    path("tax-ids/", CustomerTaxIdListCreateView.as_view(), name="billing-tax-ids"),
    path("subscriptions/", SubscriptionListView.as_view(), name="billing-subscriptions"),
    path("subscription-changes/", SubscriptionChangeRequestListCreateView.as_view(), name="billing-subscription-changes"),
    path("subscription-changes/<uuid:pk>/apply/", ApplySubscriptionChangeView.as_view(), name="billing-subscription-change-apply"),
    path("subscriptions/manual-grant/", ManualSubscriptionGrantView.as_view(), name="billing-manual-subscription-grant"),
    path("checkout-sessions/", CheckoutSessionListView.as_view(), name="billing-checkout-sessions"),
    path("checkout-sessions/create/", CreateCheckoutSessionView.as_view(), name="billing-create-checkout-session"),
    path("portal-sessions/", CustomerPortalSessionListView.as_view(), name="billing-portal-sessions"),
    path("portal-sessions/create/", CreateCustomerPortalSessionView.as_view(), name="billing-create-portal-session"),
    path("orgs/<slug:slug>/summary/", OrganizationBillingSummaryView.as_view(), name="billing-organization-summary"),
    path("orgs/<slug:slug>/entitlements/", OrganizationEntitlementsView.as_view(), name="billing-organization-entitlements"),
    path("invoices/", InvoiceListView.as_view(), name="billing-invoices"),
    path("payments/", PaymentTransactionListView.as_view(), name="billing-payments"),
    path("credit-notes/", CreditNoteListView.as_view(), name="billing-credit-notes"),
    path("credit-notes/issue/", IssueCreditNoteView.as_view(), name="billing-issue-credit-note"),
    path("refunds/", RefundRequestListCreateView.as_view(), name="billing-refunds"),
    path("refunds/<uuid:pk>/review/", ReviewRefundRequestView.as_view(), name="billing-review-refund"),
    path("dunning-cases/", DunningCaseListCreateView.as_view(), name="billing-dunning-cases"),
    path("usage-metrics/", UsageMetricListCreateView.as_view(), name="billing-usage-metrics"),
    path("usage-records/", UsageRecordListView.as_view(), name="billing-usage-records"),
    path("usage-records/record/", RecordUsageView.as_view(), name="billing-record-usage"),
    path("orgs/<slug:slug>/usage/", OrganizationUsageSummaryView.as_view(), name="billing-organization-usage"),
    path("discounts/", DiscountListCreateView.as_view(), name="billing-discounts"),
    path("promotion-codes/", PromotionCodeListCreateView.as_view(), name="billing-promotion-codes"),
    path("discount-redemptions/", DiscountRedemptionListView.as_view(), name="billing-discount-redemptions"),
    path("discounts/redeem/", RedeemDiscountView.as_view(), name="billing-redeem-discount"),
    path("addons/", AddOnListCreateView.as_view(), name="billing-addons"),
    path("addon-entitlements/", AddOnEntitlementListCreateView.as_view(), name="billing-addon-entitlements"),
    path("subscription-addons/", SubscriptionAddOnListView.as_view(), name="billing-subscription-addons"),
    path("subscription-addons/attach/", AttachSubscriptionAddOnView.as_view(), name="billing-attach-subscription-addon"),
    path("entitlement-snapshots/", EntitlementSnapshotListView.as_view(), name="billing-entitlement-snapshots"),
    path("entitlement-snapshots/recalculate/", RecalculateEntitlementSnapshotView.as_view(), name="billing-recalculate-entitlement-snapshot"),
    path("entitlement-snapshots/recalculate-with-log/", RecalculateEntitlementSnapshotWithLogView.as_view(), name="billing-recalculate-entitlement-snapshot-with-log"),
    path("entitlement-change-log/", EntitlementChangeLogListView.as_view(), name="billing-entitlement-change-log"),
    path("orgs/<slug:slug>/entitlement-snapshot/", OrganizationEntitlementSnapshotView.as_view(), name="billing-organization-entitlement-snapshot"),
    path("webhooks/events/", BillingWebhookEventListView.as_view(), name="billing-webhook-events"),
    path("webhooks/replays/", WebhookReplayRequestListView.as_view(), name="billing-webhook-replays"),
    path("webhooks/replays/create/", CreateWebhookReplayRequestView.as_view(), name="billing-webhook-replay-create"),
    path("outbox/", BillingOutboxEventListCreateView.as_view(), name="billing-outbox-events"),
    path("outbox/dispatch/", DispatchBillingOutboxView.as_view(), name="billing-outbox-dispatch"),
    path("provider-sync-states/", ProviderSyncStateListCreateView.as_view(), name="billing-provider-sync-states"),
    path("webhooks/stripe/", StripeWebhookView.as_view(), name="billing-stripe-webhook"),
]
