# Generated for django-auth-platform v29 OIDC provider hardening.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_oauthclient_authorizationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcSigningKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kid", models.CharField(max_length=120, unique=True)),
                ("algorithm", models.CharField(choices=[("RS256", "RS256"), ("ES256", "ES256"), ("EdDSA", "EdDSA")], default="RS256", max_length=16)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("active", "Active"), ("retiring", "Retiring"), ("retired", "Retired"), ("revoked", "Revoked")], default="pending", max_length=16)),
                ("public_jwk", models.JSONField(blank=True, default=dict)),
                ("private_key_reference", models.CharField(blank=True, max_length=300)),
                ("not_before", models.DateTimeField(default=django.utils.timezone.now)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retiring_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("rotation_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_oidc_keys", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OAuthScopeDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("sensitivity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("restricted", "Restricted")], default="low", max_length=16)),
                ("requires_consent", models.BooleanField(default=True)),
                ("staff_approval_required", models.BooleanField(default=False)),
                ("default_for_first_party", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="OAuthClientTrustProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trust_level", models.CharField(choices=[("first_party", "First party"), ("partner", "Partner"), ("third_party", "Third party"), ("internal_service", "Internal service")], default="first_party", max_length=32)),
                ("requires_pkce", models.BooleanField(default=True)),
                ("requires_consent_screen", models.BooleanField(default=False)),
                ("allow_offline_access", models.BooleanField(default=True)),
                ("allow_refresh_token_rotation", models.BooleanField(default=True)),
                ("allow_dynamic_scopes", models.BooleanField(default=False)),
                ("max_access_token_lifetime_seconds", models.PositiveIntegerField(default=600)),
                ("max_refresh_token_lifetime_seconds", models.PositiveIntegerField(default=1209600)),
                ("allowed_claims", models.JSONField(blank=True, default=list)),
                ("risk_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="trust_profile", to="accounts.oauthclient")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_oauth_trust_profiles", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="OidcRefreshTokenPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rotate_on_use", models.BooleanField(default=True)),
                ("reuse_detection_enabled", models.BooleanField(default=True)),
                ("revoke_family_on_reuse", models.BooleanField(default=True)),
                ("idle_timeout_seconds", models.PositiveIntegerField(default=2592000)),
                ("absolute_lifetime_seconds", models.PositiveIntegerField(default=7776000)),
                ("sender_constrained_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="refresh_token_policy", to="accounts.oauthclient")),
            ],
            options={"verbose_name": "OIDC refresh token policy", "verbose_name_plural": "OIDC refresh token policies"},
        ),
        migrations.CreateModel(
            name="OidcTokenExchangePolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("require_pkce_for_public_clients", models.BooleanField(default=True)),
                ("require_nonce_for_id_token", models.BooleanField(default=True)),
                ("allowed_grant_types", models.JSONField(blank=True, default=list)),
                ("allowed_response_types", models.JSONField(blank=True, default=list)),
                ("require_exact_redirect_uri", models.BooleanField(default=True)),
                ("reject_plain_pkce", models.BooleanField(default=True)),
                ("require_consent_for_new_scopes", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="token_exchange_policy", to="accounts.oauthclient")),
            ],
            options={"verbose_name": "OIDC token exchange policy", "verbose_name_plural": "OIDC token exchange policies"},
        ),
        migrations.CreateModel(
            name="OAuthClaimMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("claim_name", models.CharField(max_length=120)),
                ("source_path", models.CharField(help_text="Dotted source path, for example user.email or org.slug.", max_length=160)),
                ("token_type", models.CharField(choices=[("id_token", "ID token"), ("userinfo", "UserInfo"), ("access_token", "Access token")], default="id_token", max_length=24)),
                ("include_when_empty", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="claim_mappings", to="oidc_provider.oauthscopedefinition")),
            ],
            options={"ordering": ["scope__name", "token_type", "claim_name"], "unique_together": {("scope", "claim_name", "token_type")}},
        ),
        migrations.CreateModel(
            name="OAuthConsentGrant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scopes", models.JSONField(default=list)),
                ("claims", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("active", "Active"), ("revoked", "Revoked"), ("expired", "Expired")], default="active", max_length=16)),
                ("consented_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consent_grants", to="accounts.oauthclient")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="oauth_consent_grants", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-consented_at"]},
        ),
        migrations.CreateModel(
            name="OidcDiscoveryMetadataSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("issuer", models.URLField()),
                ("authorization_endpoint", models.URLField()),
                ("token_endpoint", models.URLField()),
                ("jwks_uri", models.URLField()),
                ("userinfo_endpoint", models.URLField(blank=True)),
                ("scopes_supported", models.JSONField(default=list)),
                ("claims_supported", models.JSONField(default=list)),
                ("response_types_supported", models.JSONField(default=list)),
                ("grant_types_supported", models.JSONField(default=list)),
                ("signing_alg_values_supported", models.JSONField(default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_oidc_metadata_snapshots", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="oidcsigningkey", index=models.Index(fields=["kid"], name="oidc_provid_kid_f395_idx")),
        migrations.AddIndex(model_name="oidcsigningkey", index=models.Index(fields=["status"], name="oidc_provid_status_6938_idx")),
        migrations.AddIndex(model_name="oauthscopedefinition", index=models.Index(fields=["name"], name="oidc_provid_name_2453_idx")),
        migrations.AddIndex(model_name="oauthscopedefinition", index=models.Index(fields=["is_active", "sensitivity"], name="oidc_provid_is_acti_4ce5_idx")),
        migrations.AddIndex(model_name="oauthclienttrustprofile", index=models.Index(fields=["trust_level"], name="oidc_provid_trust_l_ab68_idx")),
        migrations.AddIndex(model_name="oauthclienttrustprofile", index=models.Index(fields=["requires_consent_screen"], name="oidc_provid_require_f99e_idx")),
        migrations.AddIndex(model_name="oauthclaimmapping", index=models.Index(fields=["claim_name"], name="oidc_provid_claim_n_d1f7_idx")),
        migrations.AddIndex(model_name="oauthclaimmapping", index=models.Index(fields=["token_type", "is_active"], name="oidc_provid_token_t_7a04_idx")),
        migrations.AddIndex(model_name="oauthconsentgrant", index=models.Index(fields=["user", "client", "status"], name="oidc_provid_user_id_61ee_idx")),
        migrations.AddIndex(model_name="oauthconsentgrant", index=models.Index(fields=["client", "status"], name="oidc_provid_client__edba_idx")),
        migrations.AddIndex(model_name="oauthconsentgrant", index=models.Index(fields=["expires_at"], name="oidc_provid_expires_99ab_idx")),
        migrations.AddIndex(model_name="oidcdiscoverymetadatasnapshot", index=models.Index(fields=["issuer"], name="oidc_provid_issuer_c6de_idx")),
        migrations.AddIndex(model_name="oidcdiscoverymetadatasnapshot", index=models.Index(fields=["created_at"], name="oidc_provid_created_80ba_idx")),
    ]
