# Generated by v42 production verification upgrade
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlagInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=96, unique=True)),
                ('tier', models.CharField(choices=[('production', 'Production MVP'), ('optional', 'Optional'), ('experimental', 'Experimental')], default='optional', max_length=24)),
                ('enabled_by_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['tier', 'app_label']},
        ),
        migrations.CreateModel(
            name='VerificationSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warn', 'Warn'), ('fail', 'Fail')], max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
