from django.urls import path

from .views import (
    AdminConsoleReadinessView,
    AdminNoteDetailView,
    AdminNoteListCreateView,
    AdminWorkspacePreferenceView,
    BulkActionRequestActionView,
    BulkActionRequestListCreateView,
    CreateDashboardSnapshotView,
    DashboardSnapshotListView,
    DashboardSummaryView,
    DashboardWidgetDetailView,
    DashboardWidgetListCreateView,
    MyOperatorWorkspaceView,
    OperatorTaskActionView,
    OperatorTaskDetailView,
    OperatorTaskListCreateView,
    OrganizationAdminOverviewView,
    SavedAdminViewDetailView,
    SavedAdminViewListCreateView,
    UserAdminOverviewView,
)

urlpatterns = [
    path("readiness/", AdminConsoleReadinessView.as_view(), name="admin-console-readiness"),
    path("summary/", DashboardSummaryView.as_view(), name="admin-console-summary"),
    path("snapshots/", DashboardSnapshotListView.as_view(), name="admin-console-snapshots"),
    path("snapshots/create/", CreateDashboardSnapshotView.as_view(), name="admin-console-create-snapshot"),
    path("widgets/", DashboardWidgetListCreateView.as_view(), name="admin-console-widgets"),
    path("widgets/<slug:key>/", DashboardWidgetDetailView.as_view(), name="admin-console-widget-detail"),
    path("views/", SavedAdminViewListCreateView.as_view(), name="admin-console-saved-views"),
    path("views/<uuid:pk>/", SavedAdminViewDetailView.as_view(), name="admin-console-saved-view-detail"),
    path("tasks/", OperatorTaskListCreateView.as_view(), name="admin-console-tasks"),
    path("tasks/<uuid:pk>/", OperatorTaskDetailView.as_view(), name="admin-console-task-detail"),
    path("tasks/<uuid:pk>/action/", OperatorTaskActionView.as_view(), name="admin-console-task-action"),
    path("workspace/me/", MyOperatorWorkspaceView.as_view(), name="admin-console-my-workspace"),
    path("workspace/preferences/", AdminWorkspacePreferenceView.as_view(), name="admin-console-preferences"),
    path("bulk-actions/", BulkActionRequestListCreateView.as_view(), name="admin-console-bulk-actions"),
    path("bulk-actions/<uuid:pk>/action/", BulkActionRequestActionView.as_view(), name="admin-console-bulk-action-action"),
    path("notes/", AdminNoteListCreateView.as_view(), name="admin-console-notes"),
    path("notes/<uuid:pk>/", AdminNoteDetailView.as_view(), name="admin-console-note-detail"),
    path("users/<uuid:user_id>/overview/", UserAdminOverviewView.as_view(), name="admin-console-user-overview"),
    path("orgs/<slug:slug>/overview/", OrganizationAdminOverviewView.as_view(), name="admin-console-org-overview"),
]
